version: "3.9"
services:
  postgres:
    container_name: sandbox-postgres
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_USER=sandbox
      - POSTGRES_PASSWORD=sandbox
      - POSTGRES_DB=sandbox
    ports:
      - "6000:5432"
    volumes:
      - ./docker/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh